# .github/workflows/prison-break-ci.yml
name: Prison Break Ultimate CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    name: Validate HTML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate HTML
        run: |
          docker run -v $PWD:/data ghcr.io/validator/validator:latest \
            --verbose /data/Prison\ Break.html

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Security Scan
        uses: shiftleft/scan-action@v2
        with:
          output: reports
          scan-type: code

  deploy:
    name: Deploy to GitHub Pages
    needs: [validate, security]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

  lighthouse:
    name: Performance Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Lighthouse
        run: npm install -g lighthouse @lhci/cli

      - name: Run Lighthouse
        run: |
          lighthouse http://localhost:8080/Prison%20Break.html \
            --output=html \
            --output-path=./lighthouse-report.html \
            --chrome-flags="--headless --no-sandbox"

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: ./lighthouse-report.html
