# .github/workflows/prison-break-ci.yml
name: Prison Break Ultimate CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    name: Validate HTML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate HTML
        uses: docker://validator/validator
        with:
          args: -v /github/workspace/Prison\ Break.html

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ZAP Security Scan
        uses: zaproxy/action-baseline@v0.8.0
        with:
          target: 'http://localhost:8080/Prison%20Break.html'
          rules_file_name: 'prison-break-scan.rules'

  deploy:
    name: Deploy to GitHub Pages
    needs: [validate, security]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

  lighthouse:
    name: Performance Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start local server
        run: |
          python -m http.server 8000 &
          echo "Server running on port 8000"

      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: 'http://localhost:8000/Prison%20Break.html'
          uploadArtifacts: true
          temporaryPublicStorage: true
