# .github/workflows/prison-break-ci.yml
name: Prison Break Ultimate CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    name: Validate Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate HTML
        run: |
          wget -q https://validator.w3.org/nu/jar/nu-validator.jar
          java -jar nu-validator.jar --skip-non-html Prison\ Break.html

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    services:
      zap:
        image: owasp/zap2docker-stable
        ports:
          - 8080:8080
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.6.0
        with:
          target: 'http://localhost:8080/Prison%20Break.html'
          rules_file_name: 'prison-break-scan.rules'

  deploy:
    name: Deploy to GitHub Pages
    needs: [validate, security]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

  lighthouse:
    name: Performance Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Lighthouse
        run: npm install -g lighthouse @lhci/cli

      - name: Run Lighthouse
        run: |
          lighthouse http://localhost:8080/Prison%20Break.html \
            --output=html \
            --output-path=./lighthouse-report.html \
            --chrome-flags="--headless --no-sandbox"

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report
          path: ./lighthouse-report.html
